# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and execute script to build json for web content.

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'content.json'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.8'

    - name: Build
      run: go build -v ./...
    
    - name: Run
      run: |
        ./script

    - name: Upload JSON File
      uses: actions/upload-artifact@v3
      with:
        name: json-output
        path: content.json

    - name: Commit and Push Changes
      run: |
        git config --global user.email "noreply@github.com"
        git config --global user.name "GitHub"
        git add content.json
        git commit -m "Automatically update content.json"
        git push
